kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  Skype_Username: {{ .Values.configmap.data.username }}
  Skype_Password: {{ .Values.configmap.data.password }}
  api_key: {{ .Values.configmap.data.key }}