apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skype.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "skype.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "skype.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "skype.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "skype.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["flask" ,"run" , "--host={{ .Values.command.host }}" , "--port={{ .Values.command.port }}"]
          envFrom:
          - configMapRef:
              name: {{ .Values.configmap.name }}
          ports:
            - name: http
              containerPort: 3000