apiVersion: v1
kind: Service
metadata:
  name: {{ include "skype.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "skype.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "skype.selectorLabels" . | nindent 4 }}
